meta_product_name: "Journease"
meta_title: "Journease- Your One Stop Shop for Trip Planning"
meta_description: "Planning a trip has never been simpler! Add collaborators, access dates, contacts booking references and documents- all from one spot!"
meta_image: 'cover.jpg'
